from tkinter import*
from sympy import parse_expr
root=Tk()
root.title('simple calculaotr')
e=Entry(root,width=30,borderwidth=10,)
e.grid(row=0,column=0,columnspan=3)
def buttonadd(number):
    current= e.get()
    e.delete(0,END)
    e.insert(0, (current)+(number))
def clr():
    e.delete(0,END)
def eql():
    equation =e.get()
    parsed_expression = parse_expr(equation)
    e.delete(0,END)
    e.insert(0, parsed_expression)

button1=Button(root,text='1',padx=30,pady=10,command=lambda : buttonadd('1'))
button2=Button(root,text='2',padx=30,pady=10,command=lambda : buttonadd('2'))
button3=Button(root,text='3',padx=30,pady=10,command=lambda : buttonadd('3'))
button4=Button(root,text='4',padx=30,pady=10,command=lambda : buttonadd('4'))
button5=Button(root,text='5',padx=30,pady=10,command=lambda : buttonadd('5'))
button6=Button(root,text='6',padx=30,pady=10,command=lambda : buttonadd('6'))
button7=Button(root,text='7',padx=30,pady=10,command=lambda : buttonadd('7'))
button8=Button(root,text='8',padx=30,pady=10,command=lambda : buttonadd('8'))
button9=Button(root,text='9',padx=30,pady=10,command=lambda : buttonadd('9'))
button0=Button(root,text='0',padx=30,pady=10,command=lambda : buttonadd('0'))
buttonmul=Button(root,text='x',padx=30,pady=10,command=lambda : buttonadd('*'))
buttonpls=Button(root,text='+',padx=30,pady=10,command= lambda : buttonadd('+'))
buttonmin=Button(root,text='-',padx=30,pady=10,command=lambda : buttonadd('-'))
buttonclr=Button(root,text='clr',padx=30,pady=15,command=clr)
buttoneq=Button(root,text='=',padx=30,pady=10,command=eql)
buttoneq.grid(row=4,column=1)
buttonclr.grid(row=5,column=2)
button1.grid(row=1,column=0)
button2.grid(row=1,column=1)
button3.grid(row=1,column=2)
button4.grid(row=2,column=0)
button5.grid(row=2,column=1)
button6.grid(row=2,column=2)
button7.grid(row=3,column=0)
button8.grid(row=3,column=1)
button9.grid(row=3,column=2)
button0.grid(row=4,column=0)
buttonpls.grid(row=5,column=0)
buttonmul.grid(row=5,column=1)
buttonmin.grid(row=4,column=2)

root.mainloop()
